apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-sender-deployment
spec:
  selector:
    matchLabels:
      app: event-service-sender
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "9095"
      labels:
        app: event-service-sender
    spec:
      containers:
        - name: event-service-sender
          image: lucasnscr/event-service-sender:1.1
          ports:
            - containerPort: 9095

---
apiVersion: v1
kind: Service
metadata:
  name: event-service-sender-service
spec:
  type: ClusterIP
  selector:
    app: event-service-sender
  ports:
    - port: 9095