apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  # base64 encode of 'amqp://guest:guest@rabbitmq-keda-cluster.default.svc.cluster.local:5672'
  host: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLWtlZGEtY2x1c3Rlci5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: event-service-receiver-deployment
  pollingInterval: 20 # Optional. Default: 30 seconds
  cooldownPeriod: 120 # Optional. Default: 300 seconds
  maxReplicaCount: 20 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: kedaQ
        mode: QueueLength
        value: "5"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn